### ISSUE TITLE
Compiling on Xcode8 and swift 3

### ISSUE THREAD

**Issue by HowardTheDuck007** [tasuwo/SwiftRPG#1]
Hi!
This work appears to be great but I am having lots of issues while trying to compile.
Do you have any suggestion to help me try it out? Thank you.

**Comment by tasuwo** [comment]
Sorry for late reply and thanks for your interested.
My Xcode's version is 8.2.1 and I could compile my project (on develop branch) now.
If you couldn't do yet, please tell me in detail about why it is failed.

**Comment by HowardTheDuck007** [comment]
Hi,
thank you for your answer. Yes, now I succeeded in compiling as well.
Great work in progress. 
I am developing a text based adventure as well, and your approach for base graphics and spriteKit integration is inspiring!

Congrats!
Cristiano

 <http://www.arsbox.com/>
